# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
	config.vm.box = "bento/ubuntu-21.04"			
	config.vm.box_check_update = false
	
	config.vm.define 'mongo' do |machine|
		machine.vm.hostname = "mongo"	
		machine.vm.network 'public_network', ip: '192.168.1.2'		
		machine.vm.provider "virtualbox" do |vb|
			vb.gui = false
			vb.memory = 4096
			vb.cpus = 4
		end
	end
	
	config.vm.synced_folder 'shared', '/home/shared'
	config.vm.provision "shell", path: "provision.sh"
end